### PR TITLE
Devel mx

### PR DESCRIPTION
**Pull request by xumi1993**

### CODE REVIEW

**Comment by xumi1993** [comment]
@mnagaso I made some changes on the `CMakeLists.txt`. I am now plan to upload TomoATT to conda-forge and provide a pre-built version. I note that you change the minimum version number of `yaml-cpp` to 1.0, but the latest version is 0.8. Is there any issues raised on your side?

**Comment by mnagaso** [comment]
Hi @xumi1993

Thank you very much for your further work to publish TomoATT on conda-forge. I verified now that yaml-cpp==0.8.0 works without any problem. I was my mistake, so thank you very much for your modifying this error!

**Review by mnagaso — APPROVED** [review]
OK!

**Comment by xumi1993** [comment]
`cmake -DForce_download_externel_libs=ON ..`

**Pull request merged**
